
package br.ufc.quixada.es.pds.cobraseescadas.ui;

import br.ufc.quixada.es.pds.cobraseescadas.controle.ControladorJogo;
import javax.swing.ImageIcon;

public class JanelaLancarDados extends javax.swing.JDialog {

    private String nomeJogador;
    private int valorDado;
    private boolean lancouDado;
    private ControladorJogo controladorJogo;
    
    public JanelaLancarDados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public JanelaLancarDados(java.awt.Frame parent, boolean modal, String nomeJogador) {
        super(parent, modal);
        initComponents();
        this.nomeJogador = nomeJogador;
        this.lancouDado = false;
        this.controladorJogo = ControladorJogo.getInstance();
        this.setMensagemSolicitacao();
        this.setLocation(808, 290);
        this.setVisible(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLMensagemSolicitacao = new javax.swing.JLabel();
        jBLancarDadoClicandoNoDado = new javax.swing.JButton();
        jBLancarDado = new javax.swing.JButton();
        jBOK = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLMensagemSolicitacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLMensagemSolicitacao.setText("Mensagem de solicitação");
        jPanel1.add(jLMensagemSolicitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 26, -1, -1));

        jBLancarDadoClicandoNoDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufc/quixada/es/pds/cobraseescadas/recursos/dado3d.png"))); // NOI18N
        jBLancarDadoClicandoNoDado.setBorder(null);
        jBLancarDadoClicandoNoDado.setBorderPainted(false);
        jBLancarDadoClicandoNoDado.setContentAreaFilled(false);
        jBLancarDadoClicandoNoDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLancarDadoClicandoNoDadoActionPerformed(evt);
            }
        });
        jPanel1.add(jBLancarDadoClicandoNoDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 76, -1, -1));

        jBLancarDado.setText("Lançar Dado");
        jBLancarDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLancarDadoActionPerformed(evt);
            }
        });
        jPanel1.add(jBLancarDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 207, -1, -1));

        jBOK.setText("OK");
        jBOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOKActionPerformed(evt);
            }
        });
        jPanel1.add(jBOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 207, -1, -1));

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });
        jPanel1.add(jBSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLancarDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLancarDadoActionPerformed
      this.lancarDado();
    }//GEN-LAST:event_jBLancarDadoActionPerformed

    private void jBLancarDadoClicandoNoDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLancarDadoClicandoNoDadoActionPerformed
        this.lancarDado();
    }//GEN-LAST:event_jBLancarDadoClicandoNoDadoActionPerformed

    private void jBOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOKActionPerformed
        if(lancouDado == true){
            this.setDestinoJogadorDaVez();
            this.dispose();
        }
    }//GEN-LAST:event_jBOKActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    private void lancarDado(){
        this.valorDado = this.controladorJogo.getValorDado();
        this.setImagemDado();
        this.lancouDado = true;
    }
    
    private void setImagemDado(){
        jBLancarDadoClicandoNoDado.setIcon(new ImageIcon("src\\br\\ufc\\quixada\\es\\pds\\cobraseescadas\\recursos\\dado"+this.valorDado+".png")); 
    }
    
    public void setDestinoJogadorDaVez(){
        this.controladorJogo.setDestinoJogadorDaVez(this.valorDado);
    }
    
    private void setMensagemSolicitacao(){
         this.jLMensagemSolicitacao.setText(this.nomeJogador+", lance o dado.");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaLancarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaLancarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaLancarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaLancarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaLancarDados dialog = new JanelaLancarDados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLancarDado;
    private javax.swing.JButton jBLancarDadoClicandoNoDado;
    private javax.swing.JButton jBOK;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLMensagemSolicitacao;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
